const data = {
  projectName: 'Ankit kumar',
  client: 'joadfas',
  startFrom: '2022-04-01',
  endTo: '2022-04-21',
  note: '',
  projectType: 'Time & Materials',
  projectRateSelected: 'Project Rate option 2',
  projectRateAmount: '12,000.00',
  budget: 'Budget option 1',
  budgetReset: true,
  sendEmail: true,
  emailBudgetLimit: '80.00',
  selectedView: 'Board',
  projectManager: "Only Admin's",
};
